services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb+srv://chikaturin:123@cluster0.ltx6a.mongodb.net/?retryWrites=true&w=majority&appName=cluster0
      REDIS_HOST: 54.242.89.107
      REDIS_PORT: 6379
      KAFKA_HOST: api.wowo.htilssu.id.vn
      KAFKA_PORT: 9092
    ports:
      - "3333:3333"
