GET  http://localhost:3002/api/verify-token
{
method: 'GET'
  headers: {
    'Authorization': `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjU0NjcxNjB9.Kybdv3PcIGpORxBxfwl-qlfLsYeCVZXf_c3UTn76tJ8`
  }
  }
###
POST http://localhost:3002/login

{
    "PartnerName": "Test",
}